version: '3.1'
services:
  phx:
    image: resuelve/phoenix:elixir-1.6.6
    ports:
      - "${PHX_HOST_PORT:-4000}:${PHX_PORT:-4000}"
    volumes:
      - ./src:/app/src
      - ./src/_build/prod/rel:/app/src/_build/prod/rel
      - phx.deps:/app/src/deps
      - phx.builds:/app/src/_build
    environment:
      - MIX_ENV=${ENV:-dev}
      - PHX_PORT=${PHX_PORT:-4000}
      - PHX_URL=${PHX_HOST:-localhost}
      - PHX_SECRET_KEY_BASE=${PHX_SECRET_KEY_BASE}
    working_dir: /app/src
    command: mix phx.server

volumes:
  phx.deps:
  phx.builds: